/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import javax.swing.JOptionPane;
import modeli.ModelTabeleFakultet;
import modeli.ModelTabeleStudijskiProgram;

/**
 *
 * @author Mare
 */
public class Frm2NF extends javax.swing.JFrame {

    /**
     * Creates new form Frm2NF
     */
    public Frm2NF(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        
        setTitle("2NF");
        setLocationRelativeTo(null);
        
        ModelTabeleFakultet model=new ModelTabeleFakultet(this);
        tblFakulteti.setModel(model);
        
        ModelTabeleStudijskiProgram model1=new ModelTabeleStudijskiProgram(this);
        tblStudijskiProgrami.setModel(model1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnKreirajFakultet = new javax.swing.JButton();
        btnIzmeniFakultet = new javax.swing.JButton();
        btnObrisiFakultet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFakulteti = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudijskiProgrami = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnKreirajStudijskiProgram = new javax.swing.JButton();
        btnIzmeniStudijskiProgram = new javax.swing.JButton();
        btnObrisiStudijskiProgram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Fakulteti");

        btnKreirajFakultet.setText("Kreiraj");
        btnKreirajFakultet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajFakultetActionPerformed(evt);
            }
        });

        btnIzmeniFakultet.setText("Izmeni");
        btnIzmeniFakultet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniFakultetActionPerformed(evt);
            }
        });

        btnObrisiFakultet.setText("Obrisi");
        btnObrisiFakultet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiFakultetActionPerformed(evt);
            }
        });

        tblFakulteti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFakulteti);

        tblStudijskiProgrami.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStudijskiProgrami);

        jLabel2.setText("Studijski programi");

        btnKreirajStudijskiProgram.setText("Kreiraj");
        btnKreirajStudijskiProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajStudijskiProgramActionPerformed(evt);
            }
        });

        btnIzmeniStudijskiProgram.setText("Izmeni");
        btnIzmeniStudijskiProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStudijskiProgramActionPerformed(evt);
            }
        });

        btnObrisiStudijskiProgram.setText("Obrisi");
        btnObrisiStudijskiProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiStudijskiProgramActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIzmeniFakultet)
                            .addComponent(btnKreirajFakultet)
                            .addComponent(btnObrisiFakultet)
                            .addComponent(btnKreirajStudijskiProgram)
                            .addComponent(btnIzmeniStudijskiProgram)
                            .addComponent(btnObrisiStudijskiProgram)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKreirajFakultet)
                        .addGap(36, 36, 36)
                        .addComponent(btnIzmeniFakultet)
                        .addGap(44, 44, 44)
                        .addComponent(btnObrisiFakultet))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKreirajStudijskiProgram)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniStudijskiProgram)
                        .addGap(28, 28, 28)
                        .addComponent(btnObrisiStudijskiProgram)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajFakultetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajFakultetActionPerformed
        new FrmFakultet(this, true).setVisible(true);
    }//GEN-LAST:event_btnKreirajFakultetActionPerformed

    private void btnIzmeniFakultetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniFakultetActionPerformed
        int odabraniFakultet=tblFakulteti.getSelectedRow();
        
        if(odabraniFakultet<0){
            JOptionPane.showMessageDialog(this, "Nije odabran fakultet", "GRESKA PRI UCITAVANJU", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnIzmeniFakultetActionPerformed

    private void btnObrisiFakultetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiFakultetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisiFakultetActionPerformed

    private void btnKreirajStudijskiProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajStudijskiProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKreirajStudijskiProgramActionPerformed

    private void btnIzmeniStudijskiProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStudijskiProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzmeniStudijskiProgramActionPerformed

    private void btnObrisiStudijskiProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiStudijskiProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisiStudijskiProgramActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeniFakultet;
    private javax.swing.JButton btnIzmeniStudijskiProgram;
    private javax.swing.JButton btnKreirajFakultet;
    private javax.swing.JButton btnKreirajStudijskiProgram;
    private javax.swing.JButton btnObrisiFakultet;
    private javax.swing.JButton btnObrisiStudijskiProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblFakulteti;
    private javax.swing.JTable tblStudijskiProgrami;
    // End of variables declaration//GEN-END:variables

}
