/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Fakultet;
import domen.Univerzitet;
import java.awt.Frame;
import java.awt.List;
import java.util.ArrayList;
import logika.Kontroler;

/**
 *
 * @author Mare
 */
public class FrmFakultet extends javax.swing.JDialog {
    
    ModForme mod=ModForme.KREIRAJ;
    
    private Fakultet f;

    /**
     * Creates new form FrmFakultet
     */
    public FrmFakultet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        srediFormu(mod,f);
    }

    FrmFakultet(FrmFakultet aThis, boolean modal, ModForme mod, Fakultet f) {
        super(aThis, modal);
        initComponents();

        this.f = f;
        srediFormu(mod, f);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSifraFakulteta = new javax.swing.JLabel();
        txtSifraFakulteta = new javax.swing.JTextField();
        txtNazivFakulteta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAdresaFakulteta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbSifraUniverziteta = new javax.swing.JComboBox<>();
        btnKreiraj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblSifraFakulteta.setText("Sifra fakulteta:");

        jLabel2.setText("Naziv:");

        jLabel3.setText("Adresa:");

        jLabel4.setText("Sifra univerziteta:");

        btnKreiraj.setText("Kreiraj");

        btnIzmeni.setText("Izmeni");

        btnObrisi.setText("Obrisi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSifraFakulteta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnKreiraj)
                    .addComponent(txtSifraFakulteta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNazivFakulteta)
                        .addComponent(txtAdresaFakulteta)
                        .addComponent(cmbSifraUniverziteta, 0, 256, Short.MAX_VALUE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSifraFakulteta)
                    .addComponent(txtSifraFakulteta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivFakulteta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdresaFakulteta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbSifraUniverziteta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnKreiraj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIzmeni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisi)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void srediFormu(ModForme mod, Fakultet f) {
        setLocationRelativeTo(null);
        
        ArrayList<Univerzitet> univerziteti=Kontroler.getInstanca().vratiUniverzitete();
        
        for (Univerzitet u : univerziteti) {
            cmbSifraUniverziteta.addItem(u);
        }
        switch (mod) {
            case KREIRAJ:
                setTitle("KREIRAJ FAKULTET");
                
                btnKreiraj.setVisible(true);
                btnIzmeni.setVisible(false);
                btnObrisi.setVisible(false);
                break;
            case IZMENI:
                setTitle("IZMENI");
                
                txtSifraFakulteta.setText(String.valueOf(f.getSifraFakulteta()));
                txtNazivFakulteta.setText(f.getNazivFakulteta());
                txtAdresaFakulteta.setText(f.getAdresaFakulteta());
                cmbSifraUniverziteta.setSelectedItem(f.getSifraUniverziteta());
                
                btnKreiraj.setVisible(false);
                btnIzmeni.setVisible(true);
                btnObrisi.setVisible(false);
                break;
            case OBRISI:
                
                break;
            default:
                throw new AssertionError();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JComboBox<Object> cmbSifraUniverziteta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblSifraFakulteta;
    private javax.swing.JTextField txtAdresaFakulteta;
    private javax.swing.JTextField txtNazivFakulteta;
    private javax.swing.JTextField txtSifraFakulteta;
    // End of variables declaration//GEN-END:variables
}
