/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

/**
 *
 * @author Mare
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        
        setTitle("PRIJAVA NA MASTER STUDIJE");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuPrikazi = new javax.swing.JMenu();
        jmiDenormalizacija2NF = new javax.swing.JMenuItem();
        jmiDenormalizacija3NF = new javax.swing.JMenuItem();
        jmiHorizontalnoParticionisanje = new javax.swing.JMenuItem();
        jmiVertikalnoParticionisanje = new javax.swing.JMenuItem();
        jmiHardCodedValues = new javax.swing.JMenuItem();
        jmiStoringDerivableValues = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuPrikazi.setText("Prikazi");

        jmiDenormalizacija2NF.setText("Denormalizacija 2NF");
        jmiDenormalizacija2NF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDenormalizacija2NFActionPerformed(evt);
            }
        });
        jMenuPrikazi.add(jmiDenormalizacija2NF);

        jmiDenormalizacija3NF.setText("Denormalizacija 3NF");
        jmiDenormalizacija3NF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDenormalizacija3NFActionPerformed(evt);
            }
        });
        jMenuPrikazi.add(jmiDenormalizacija3NF);

        jmiHorizontalnoParticionisanje.setText("Horizontalno particionisanje");
        jmiHorizontalnoParticionisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHorizontalnoParticionisanjeActionPerformed(evt);
            }
        });
        jMenuPrikazi.add(jmiHorizontalnoParticionisanje);

        jmiVertikalnoParticionisanje.setText("Vertikalno particionisanje");
        jmiVertikalnoParticionisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVertikalnoParticionisanjeActionPerformed(evt);
            }
        });
        jMenuPrikazi.add(jmiVertikalnoParticionisanje);

        jmiHardCodedValues.setText("Hard-Coded Values");
        jmiHardCodedValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiHardCodedValuesActionPerformed(evt);
            }
        });
        jMenuPrikazi.add(jmiHardCodedValues);

        jmiStoringDerivableValues.setText("Storing Derivable Values");
        jmiStoringDerivableValues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiStoringDerivableValuesActionPerformed(evt);
            }
        });
        jMenuPrikazi.add(jmiStoringDerivableValues);

        jMenuBar.add(jMenuPrikazi);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiDenormalizacija2NFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDenormalizacija2NFActionPerformed
        new Frm2NF(this, true).setVisible(true);
    }//GEN-LAST:event_jmiDenormalizacija2NFActionPerformed

    private void jmiDenormalizacija3NFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDenormalizacija3NFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiDenormalizacija3NFActionPerformed

    private void jmiHorizontalnoParticionisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHorizontalnoParticionisanjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiHorizontalnoParticionisanjeActionPerformed

    private void jmiVertikalnoParticionisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVertikalnoParticionisanjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiVertikalnoParticionisanjeActionPerformed

    private void jmiHardCodedValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiHardCodedValuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiHardCodedValuesActionPerformed

    private void jmiStoringDerivableValuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiStoringDerivableValuesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiStoringDerivableValuesActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuPrikazi;
    private javax.swing.JMenuItem jmiDenormalizacija2NF;
    private javax.swing.JMenuItem jmiDenormalizacija3NF;
    private javax.swing.JMenuItem jmiHardCodedValues;
    private javax.swing.JMenuItem jmiHorizontalnoParticionisanje;
    private javax.swing.JMenuItem jmiStoringDerivableValues;
    private javax.swing.JMenuItem jmiVertikalnoParticionisanje;
    // End of variables declaration//GEN-END:variables
}
